export const mockProjectData = {
    "effectiveMsgSize": 0,
    "tasks": [
        {
            "taskId": "Task_39",
            "projectId": "youhuixianxiang",
            "name": "端控和浮层链接任务",
            "content": "完成端控和浮层链接的相关工作，包括端控由赵述佳和刁洪亮负责，浮层链接由郝泽楠负责。",
            "createTime": "2024-09-26T07:21:52.852Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": null,
            "creatorId": "赵苗m",
            "messageIds": [
                "145"
            ]
        },
        {
            "taskId": "Task_60",
            "projectId": "youhuixianxiang",
            "name": "技术Wiki更新",
            "content": "将技术文档和相关信息放入技术Wiki中。",
            "createTime": "2024-10-08T11:38:14.474Z",
            "deadline": null,
            "status": "done",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "谭鹏yy",
            "creatorId": "谭鹏yy",
            "messageIds": [
                "243",
                "245"
            ]
        },
        {
            "taskId": "Task_38",
            "projectId": "youhuixianxiang",
            "name": "订单详情页开发",
            "content": "订单详情页开发，涉及到辅营交易和售后模块，需要增加三个接口改动。",
            "createTime": "2024-09-26T10:43:15Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "赵苗m",
            "creatorId": "赵苗m",
            "messageIds": [
                "114",
                "115",
                "116",
                "117",
                "118",
                "119",
                "120",
                "121",
                "123",
                "125",
                "126",
                "127",
                "129",
                "131",
                "132",
                "133",
                "134",
                "135",
                "136",
                "137",
                "138",
                "139",
                "140",
                "141",
                "142",
                "143"
            ]
        },
        {
            "taskId": "Task_40",
            "projectId": "youhuixianxiang",
            "name": "确认支付完成页和订单详情页开发",
            "content": "确认支付完成页和订单详情页的开发工作，包括只做app版本和考虑合单逻辑。",
            "createTime": "2024-09-26T08:30:13.163Z",
            "deadline": null,
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": null,
            "creatorId": "刁洪亮",
            "messageIds": [
                "166",
                "167",
                "170",
                "171"
            ]
        },
        {
            "taskId": "Task_41",
            "projectId": "youhuixianxiang",
            "name": "接口API文档编写",
            "content": "编写并提供接口API文档，包括预计算接口和授权结果同步接口。",
            "createTime": "2024-09-26T12:30:04.488Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": null,
            "creatorId": "蔡宜身",
            "messageIds": [
                "173",
                "175"
            ]
        },
        {
            "taskId": "Task_62",
            "projectId": "youhuixianxiang",
            "name": "afterPayApolloHotelModule信息确认",
            "content": "确认afterPayApolloHotelModule模块的具体信息字段。",
            "createTime": "2024-10-09T02:18:44.29Z",
            "deadline": null,
            "status": "done",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "黄启孟",
            "creatorId": "黄启孟",
            "messageIds": [
                "256",
                "258",
                "259",
                "260",
                "261",
                "262",
                "263"
            ]
        },
        {
            "taskId": "Task_63",
            "projectId": "youhuixianxiang",
            "name": "机酒优惠享营销字段确认",
            "content": "确认activitySpecialType字段代表机酒优惠享营销的具体值，并更新到技术方案的Wiki中。",
            "createTime": null,
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "278",
                "279",
                "280",
                "281",
                "282",
                "283",
                "284",
                "285",
                "286",
                "287",
                "288",
                "289",
                "290",
                "291",
                "292",
                "293",
                "294",
                "295",
                "296"
            ]
        },
        {
            "taskId": "Task_64",
            "projectId": "youhuixianxiang",
            "name": null,
            "content": "空",
            "createTime": null,
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": []
        },
        {
            "taskId": "Task_61",
            "projectId": "youhuixianxiang",
            "name": "国际支付完成页UI确认",
            "content": "确认国际支付完成页的UI设计是否与当前线上版本一致。",
            "createTime": "2024-10-08T13:04:20.564Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "刁洪亮",
            "creatorId": "刁洪亮",
            "messageIds": [
                "249",
                "250",
                "251",
                "252",
                "253",
                "254",
                "255",
                "257"
            ]
        },
        {
            "taskId": "Task_37",
            "projectId": "youhuixianxiang",
            "name": "P1需求提测",
            "content": "P1需求提测，和QA对的提测时间节点是10月8号提测，请大家提前预留排期资源。",
            "createTime": "2024-09-11T15:17:30Z",
            "deadline": "2024-10-08T00:00:00Z",
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "陈民华",
            "creatorId": "陈民华",
            "messageIds": [
                "13"
            ]
        },
        {
            "taskId": "Task_65",
            "projectId": "youhuixianxiang",
            "name": "优化支付流程",
            "content": "优化支付流程，涉及后付收银台的拉起和支付前校验逻辑。",
            "createTime": "2024-09-26T15:05:09Z",
            "deadline": null,
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "郝泽楠",
            "creatorId": "赵苗m",
            "messageIds": [
                "136",
                "137",
                "138",
                "139",
                "140",
                "141",
                "142",
                "143",
                "144",
                "145",
                "146",
                "147",
                "148",
                "149",
                "150",
                "151",
                "152",
                "153",
                "154",
                "155",
                "157",
                "158",
                "159",
                "160",
                "161",
                "162",
                "164",
                "165",
                "166",
                "167",
                "168",
                "169",
                "170",
                "171",
                "172",
                "173",
                "174",
                "175",
                "176",
                "177",
                "178",
                "179",
                "180",
                "181",
                "182",
                "183",
                "184",
                "185",
                "186",
                "187",
                "188",
                "189",
                "190",
                "191",
                "192",
                "193",
                "194",
                "195",
                "196",
                "197",
                "198",
                "199",
                "200",
                "201",
                "202",
                "203"
            ]
        },
        {
            "taskId": "Task_66",
            "projectId": "youhuixianxiang",
            "name": "接口API文档编写",
            "content": "@赵述佳 你那边接口api给一下吧",
            "createTime": null,
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "173"
            ]
        },
        {
            "taskId": "Task_67",
            "projectId": "youhuixianxiang",
            "name": "联调排期",
            "content": "重新定联调日期，暂定12号进行联调。",
            "createTime": "2024-10-09T16:16:33Z",
            "deadline": "2024-10-12T23:59:59Z",
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "陈民华",
            "creatorId": "赵述佳",
            "messageIds": [
                "348",
                "352",
                "354",
                "364"
            ]
        },
        {
            "taskId": "Task_68",
            "projectId": "youhuixianxiang",
            "name": "支付中心接口问题",
            "content": "确认支付中心返回的链接类型，是否为scheme。",
            "createTime": "2024-10-09T16:19:33Z",
            "deadline": null,
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": "黄启孟",
            "creatorId": "黄启孟",
            "messageIds": [
                "349",
                "350",
                "356",
                "357",
                "362"
            ]
        },
        {
            "taskId": "Task_69",
            "projectId": "youhuixianxiang",
            "name": "前端联调",
            "content": "前端联调乘机人变更接口、前端机酒优惠享UI展示和交互逻辑、生单接口等。",
            "createTime": "2024-10-10T10:47:03Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "黄启孟",
            "creatorId": null,
            "messageIds": [
                "384",
                "385"
            ]
        },
        {
            "taskId": "Task_70",
            "projectId": "youhuixianxiang",
            "name": "CMS页面适配问题",
            "content": "适配国内CMS页面，解决关闭按钮事件和页面显示问题。",
            "createTime": "2024-10-10T15:01:14Z",
            "deadline": null,
            "status": "pending",
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "473",
                "474",
                "475",
                "476",
                "477",
                "478",
                "479",
                "480",
                "481",
                "482",
                "483",
                "484",
                "485",
                "486",
                "487",
                "488",
                "489",
                "490",
                "491",
                "492",
                "493",
                "494",
                "495",
                "496",
                "497",
                "498",
                "499"
            ]
        },
        {
            "taskId": "Task_71",
            "projectId": "youhuixianxiang",
            "name": "国际链接适配国内CMS",
            "content": "适配国际机酒连订优惠填单页的浮层，点击查看详细规则出CMS页面，解决网页内容不显示的问题。",
            "createTime": "2024-10-10T14:00:52Z",
            "deadline": null,
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "郝泽楠",
            "creatorId": "郝泽楠",
            "messageIds": [
                "447",
                "448",
                "452",
                "457",
                "473",
                "474",
                "475",
                "476",
                "477",
                "478",
                "480",
                "481",
                "482",
                "483",
                "484",
                "485",
                "486",
                "487",
                "488",
                "489",
                "490",
                "491",
                "492",
                "493",
                "494",
                "495",
                "496",
                "497",
                "498",
                "499",
                "500",
                "501",
                "502",
                "503",
                "504",
                "505"
            ]
        },
        {
            "taskId": "Task_72",
            "projectId": "youhuixianxiang",
            "name": "国内售后和辅营交互对齐",
            "content": "@赵晓威 对下国内售后和辅营的交互，确定单退和合单退的流程。",
            "createTime": "2024-10-10T14:35:51Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "何钢",
            "creatorId": "何钢",
            "messageIds": [
                "459",
                "461",
                "462",
                "463",
                "464"
            ]
        },
        {
            "taskId": "Task_73",
            "projectId": "youhuixianxiang",
            "name": "保险支付方式问题",
            "content": "@郝泽楠 保险当前不走后付的原因是支付宝和微信不支持保险的免密支付。",
            "createTime": null,
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "460",
                "465",
                "466",
                "467"
            ]
        },
        {
            "taskId": "Task_74",
            "projectId": "youhuixianxiang",
            "name": null,
            "content": "空",
            "createTime": null,
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "510"
            ]
        },
        {
            "taskId": "Task_75",
            "projectId": "youhuixianxiang",
            "name": "联调进度跟踪",
            "content": "跟踪售前、后服务、收银台、主站、营销和活动的联调进度，解决阻塞问题。",
            "createTime": "2024-10-12T16:27:36Z",
            "deadline": "2024-10-18T00:00:00Z",
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "蔡宜身",
            "creatorId": "蔡宜身",
            "messageIds": [
                "567",
                "579",
                "580",
                "581"
            ]
        },
        {
            "taskId": "Task_76",
            "projectId": "youhuixianxiang",
            "name": "扣款接口字段补充",
            "content": "在扣款接口中增加总单回调的扣款金额和扣款方式字段。",
            "createTime": "2024-10-12T16:17:05Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "谭鹏yy",
            "creatorId": "谭鹏yy",
            "messageIds": [
                "565",
                "566"
            ]
        },
        {
            "taskId": "Task_77",
            "projectId": "youhuixianxiang",
            "name": "环境问题修复",
            "content": "解决填单页服务器异常和环境问题。",
            "createTime": "2024-10-12T20:52:04Z",
            "deadline": null,
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": "黄启孟",
            "creatorId": "黄启孟",
            "messageIds": [
                "584",
                "585",
                "592",
                "593",
                "666",
                "667"
            ]
        },
        {
            "taskId": "Task_78",
            "projectId": "youhuixianxiang",
            "name": "订单状态修改",
            "content": "修改订单状态为出票完成",
            "createTime": "2024-10-15T11:13:13Z",
            "deadline": null,
            "status": "done",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "赵述佳",
            "creatorId": "刁洪亮",
            "messageIds": [
                "668",
                "669",
                "671",
                "674",
                "691",
                "692",
                "693",
                "694",
                "695",
                "696",
                "697",
                "698",
                "700"
            ]
        },
        {
            "taskId": "Task_79",
            "projectId": "youhuixianxiang",
            "name": "调试Apollo接口",
            "content": "调试Apollo接口，解决机酒优惠享问题",
            "createTime": "2024-10-15T11:16:52Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": "张航玮",
            "creatorId": "黄启孟",
            "messageIds": [
                "672",
                "673",
                "675",
                "676",
                "678",
                "679",
                "680",
                "681",
                "682",
                "683",
                "684",
                "685",
                "686",
                "688",
                "689"
            ]
        },
        {
            "taskId": "Task_80",
            "projectId": "youhuixianxiang",
            "name": "环境调试与配置",
            "content": "调试环境并配置相关接口，确保请求路由正确",
            "createTime": "2024-10-15T11:54:29Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "赵述佳",
            "creatorId": "刁洪亮",
            "messageIds": [
                "707",
                "708",
                "709",
                "710",
                "711",
                "712",
                "713",
                "714",
                "715",
                "716",
                "717",
                "718",
                "719",
                "720",
                "721",
                "722",
                "723",
                "724",
                "725"
            ]
        },
        {
            "taskId": "Task_81",
            "projectId": "youhuixianxiang",
            "name": "订单详情页UI图配置",
            "content": "配置订单详情页的UI图和文案内容，确保页面显示正确。",
            "createTime": "2024-10-15T14:33:29Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "赵述佳",
            "creatorId": "刁洪亮",
            "messageIds": [
                "746",
                "747",
                "748",
                "751",
                "752",
                "753",
                "754",
                "755"
            ]
        },
        {
            "taskId": "Task_82",
            "projectId": "youhuixianxiang",
            "name": "优化搜索接口性能",
            "content": "针对机票查询接口优化，主要包括：1. 实现Redis缓存层减少DB查询 2. 优化查询SQL语句",
            "createTime": "2024-10-15T16:38:04Z",
            "deadline": null,
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "许彤瑶",
            "creatorId": "许彤瑶",
            "messageIds": [
                "795",
                "797"
            ]
        },
        {
            "taskId": "Task_83",
            "projectId": "youhuixianxiang",
            "name": "营销生单失败处理",
            "content": "营销生单失败，机票生单走老流程，不享受优惠",
            "createTime": "2024-10-15T16:47:11Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": "许彤瑶",
            "creatorId": "许彤瑶",
            "messageIds": [
                "797"
            ]
        },
        {
            "taskId": "Task_84",
            "projectId": "youhuixianxiang",
            "name": "兼容合单逻辑",
            "content": "apollo要兼容合单逻辑，合单下部分出本次活动，部分出老活动，需要apollo控制优先级，统一优先返回新活动",
            "createTime": "2024-10-15T16:50:09Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": null,
            "creatorId": "刁洪亮",
            "messageIds": [
                "799"
            ]
        },
        {
            "taskId": "Task_85",
            "projectId": "youhuixianxiang",
            "name": "售后部分联调",
            "content": "售后部分的联调需要各自留一天和后端联调，并且不能在同一天，帮忙确认个时间",
            "createTime": "2024-10-16T10:39:24Z",
            "deadline": null,
            "status": "pending",
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "873",
                "874",
                "890"
            ]
        },
        {
            "taskId": "Task_86",
            "projectId": "youhuixianxiang",
            "name": "环境配置调整",
            "content": "由于之前的环境不可用，赵述佳更换了一个新的环境。",
            "createTime": "2024-10-15T14:58:27Z",
            "deadline": null,
            "status": "done",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "赵述佳",
            "creatorId": "赵述佳",
            "messageIds": [
                "764"
            ]
        },
        {
            "taskId": "Task_87",
            "projectId": "youhuixianxiang",
            "name": "环境冲突排查",
            "content": "张航玮发现两个环境可能有冲突，导致主站标识消失。赵述佳询问是否绑定了两个环境，张航玮确认。",
            "createTime": "2024-10-15T15:02:54Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": "张航玮",
            "creatorId": "张航玮",
            "messageIds": [
                "768",
                "769",
                "770"
            ]
        },
        {
            "taskId": "Task_88",
            "projectId": "youhuixianxiang",
            "name": "数据缺失问题排查",
            "content": "黄启孟报告数据缺失问题，赵述佳询问是否有trace，黄启孟提供了trace信息。",
            "createTime": "2024-10-15T15:06:12Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": "黄启孟",
            "creatorId": "黄启孟",
            "messageIds": [
                "771",
                "772",
                "773"
            ]
        },
        {
            "taskId": "Task_89",
            "projectId": "youhuixianxiang",
            "name": "Checklist会议安排",
            "content": "@刘煜枝 提议明天下午3:30在8层圆桌对下checklist。",
            "createTime": "2024-10-15T15:31:08Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "process",
            "assigneeId": null,
            "creatorId": "刘煜枝",
            "messageIds": [
                "784",
                "785"
            ]
        },
        {
            "taskId": "Task_90",
            "projectId": "youhuixianxiang",
            "name": "Booking提示条优先级配置",
            "content": "@许彤瑶 提到booking提示条优先级不可配置，后端写死。",
            "createTime": "2024-10-15T16:38:04Z",
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "795",
                "798"
            ]
        },
        {
            "taskId": "Task_91",
            "projectId": "youhuixianxiang",
            "name": "修改case",
            "content": "1. list、ota的标签展示、明细浮层 2. booking页提示条样式控制 3. 后付收银台接入支付宝、银行卡 4. 是否可切换在线支付 5. 支付前校验失败处理 6. 跳转第三方授权后返回后付收银台页面 7. 扣款中状态的浮层不可关闭 8. 订单包含保险不展示金额 9. 订单包含保险点击同意并授权后不做支付前校验 10. 支付完成页机酒连订模块调整 11. 跳转酒店时带城市、日期，入离店日期用到达日期和到达日期+1 12. 待离店点击跳转订单列表页 13. 订单状态为待出票展示任务banner，出票失败任务状态变为取消 14. 任务状态流转case补充 15. 订单详情页展示扣款中状态",
            "createTime": "2024-10-16T19:12:37Z",
            "deadline": null,
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "许彤瑶",
            "creatorId": "许彤瑶",
            "messageIds": [
                "975"
            ]
        },
        {
            "taskId": "Task_92",
            "projectId": "youhuixianxiang",
            "name": "确认booking底部按钮配置",
            "content": "确认booking底部按钮位置和颜色配置控制",
            "createTime": "2024-10-16T19:12:37Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "question",
            "assigneeId": null,
            "creatorId": "许彤瑶",
            "messageIds": [
                "975",
                "980",
                "982"
            ]
        },
        {
            "taskId": "Task_93",
            "projectId": "youhuixianxiang",
            "name": "确认附加服务页返回booking的生单状态",
            "content": "确认从附加服务页返回booking时生单未支付状态是否会创建失败，以及任务处理方式",
            "createTime": "2024-10-16T19:12:37Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "question",
            "assigneeId": null,
            "creatorId": "许彤瑶",
            "messageIds": [
                "975"
            ]
        },
        {
            "taskId": "Task_94",
            "projectId": "youhuixianxiang",
            "name": "确认收银台挽留弹窗跳转路径",
            "content": "确认收银台挽留弹窗的离开按钮跳转路径",
            "createTime": "2024-10-16T19:12:37Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "question",
            "assigneeId": null,
            "creatorId": "许彤瑶",
            "messageIds": [
                "975"
            ]
        },
        {
            "taskId": "Task_95",
            "projectId": "youhuixianxiang",
            "name": "确认还款完成后订单详情页刷新情况",
            "content": "确认还款完成后返回订单详情页时是否会刷新",
            "createTime": "2024-10-16T19:12:37Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "question",
            "assigneeId": null,
            "creatorId": "许彤瑶",
            "messageIds": [
                "975"
            ]
        },
        {
            "taskId": "Task_96",
            "projectId": "youhuixianxiang",
            "name": "支持不同用户配置不同任务金额和活动",
            "content": "空",
            "createTime": null,
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": null
        },
        {
            "taskId": "Task_97",
            "projectId": "youhuixianxiang",
            "name": "配置支付前校验的URL",
            "content": "配置支付前校验的URL为/api/pay/creditPrepay，并确认对应域名。",
            "createTime": "2024-10-17T16:00:04Z",
            "deadline": null,
            "status": "done",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "肖杨",
            "creatorId": "肖杨",
            "messageIds": [
                "1083",
                "1086",
                "1089",
                "1091"
            ]
        },
        {
            "taskId": "Task_98",
            "projectId": "youhuixianxiang",
            "name": "确认签约协议号字段",
            "content": "确认签约协议号字段在支付中心的名称，并与支付中心保持一致。",
            "createTime": "2024-10-17T15:56:37Z",
            "deadline": null,
            "status": "done",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "蔡宜身",
            "creatorId": "蔡宜身",
            "messageIds": [
                "1078",
                "1079",
                "1081",
                "1085",
                "1087",
                "1096"
            ]
        },
        {
            "taskId": "Task_99",
            "projectId": "youhuixianxiang",
            "name": "确认用户名或userId的必要性",
            "content": "确认用户名或userId在接口请求中的必要性，并决定是否使用userId替代用户名。",
            "createTime": "2024-10-17T16:02:31Z",
            "deadline": null,
            "status": "done",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "question",
            "assigneeId": "蔡宜身",
            "creatorId": "蔡宜身",
            "messageIds": [
                "1088",
                "1090",
                "1092"
            ]
        },
        {
            "taskId": "Task_100",
            "projectId": "youhuixianxiang",
            "name": "更新API以包含userId字段",
            "content": "在API中添加userId字段，并更新相应的调用。",
            "createTime": "2024-10-17T16:11:09Z",
            "deadline": null,
            "status": "done",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "蔡宜身",
            "creatorId": "蔡宜身",
            "messageIds": [
                "1108",
                "1110"
            ]
        },
        {
            "taskId": "Task_101",
            "projectId": "youhuixianxiang",
            "name": "配置中台测试商户号和密钥",
            "content": "配置中台测试商户号8001011及其对应的公钥和私钥，并进行相关测试。",
            "createTime": "2024-10-18T10:39:56Z",
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "1155",
                "1159",
                "1160",
                "1161",
                "1162",
                "1167",
                "1169",
                "1171"
            ]
        },
        {
            "taskId": "Task_102",
            "projectId": "youhuixianxiang",
            "name": "支付公钥验签问题",
            "content": "解决支付返回值验签失败的问题，涉及公钥配置和验签逻辑。",
            "createTime": "2024-10-21T15:14:44Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": "肖杨",
            "creatorId": "肖杨",
            "messageIds": [
                "1205",
                "1206",
                "1207",
                "1208",
                "1209",
                "1210",
                "1211",
                "1212",
                "1213",
                "1214",
                "1215",
                "1216",
                "1217",
                "1218",
                "1219",
                "1220",
                "1221",
                "1222",
                "1223",
                "1224",
                "1225",
                "1226",
                "1227",
                "1228",
                "1229",
                "1230"
            ]
        },
        {
            "taskId": "Task_103",
            "projectId": "youhuixianxiang",
            "name": "后付收银台支付失败处理",
            "content": "处理后付收银台支付失败的情况，确保支付流程顺畅。",
            "createTime": "2024-10-21T16:12:04Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": null,
            "creatorId": "何钢",
            "messageIds": [
                "1218",
                "1219",
                "1220",
                "1221",
                "1222",
                "1223"
            ]
        },
        {
            "taskId": "Task_104",
            "projectId": "youhuixianxiang",
            "name": "信用付营销活动处理",
            "content": "处理信用付营销活动的相关问题，确保营销活动正确应用。",
            "createTime": null,
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "1303",
                "1304",
                "1305",
                "1306",
                "1307"
            ]
        },
        {
            "taskId": "Task_105",
            "projectId": "youhuixianxiang",
            "name": "优化支付流程",
            "content": "优化支付流程，包括调整授权结果通知的URL，修复带保险场景下的支付问题，确保机酒优惠享功能正常。",
            "createTime": "2024-10-22T14:11:29Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "肖杨",
            "creatorId": "肖杨",
            "messageIds": [
                "1294",
                "1342",
                "1349",
                "1350",
                "1351",
                "1352",
                "1353",
                "1354",
                "1355",
                "1356",
                "1357"
            ]
        },
        {
            "taskId": "Task_106",
            "projectId": "youhuixianxiang",
            "name": "调整支付流程倒计时逻辑",
            "content": "将支付流程中的倒计时逻辑调整为当前时间+配置的时间段，默认设置为15分钟。",
            "createTime": "2024-10-22T17:12:36Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "肖杨",
            "creatorId": "肖杨",
            "messageIds": [
                "1358",
                "1359",
                "1361",
                "1362",
                "1363"
            ]
        },
        {
            "taskId": "Task_107",
            "projectId": "youhuixianxiang",
            "name": "优化营销活动处理逻辑",
            "content": "优化营销活动处理逻辑，确保多个营销活动可以正确处理和返还价格。",
            "createTime": "2024-10-22T15:33:11Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "improvement",
            "assigneeId": "谭鹏yy",
            "creatorId": "谭鹏yy",
            "messageIds": [
                "1324",
                "1325"
            ]
        },
        {
            "taskId": "Task_112",
            "projectId": "youhuixianxiang",
            "name": "对辅营售前case进行讨论",
            "content": "王颖提议在20:10对辅营售前case进行讨论，郝泽楠建议改为21:00。",
            "createTime": "2024-10-22T11:49:48.897Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "discussion",
            "assigneeId": "王颖yw",
            "creatorId": "王颖yw",
            "messageIds": [
                "1385",
                "1398",
                "1424"
            ]
        },
        {
            "taskId": "Task_113",
            "projectId": "youhuixianxiang",
            "name": "支付完成页问题修复",
            "content": "刁洪亮提出支付完成页的几个问题需要修复，包括标题图片大小调整、标签样式控制、模块底部空白控制和i标浮层内容问题。",
            "createTime": "2024-10-22T12:15:10.321Z",
            "deadline": null,
            "status": "pending",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": "黄启孟",
            "creatorId": "刁洪亮",
            "messageIds": [
                "1387",
                "1403",
                "1404",
                "1420",
                "1425",
                "1426"
            ]
        },
        {
            "taskId": "Task_114",
            "projectId": "youhuixianxiang",
            "name": "list页预计算实现讨论",
            "content": "赵述佳和蔡宜身讨论list页用预计算方式实现的可行性。",
            "createTime": "2024-10-22T12:15:36.783Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "discussion",
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "1389",
                "1390",
                "1391",
                "1392",
                "1394",
                "1395",
                "1396",
                "1397"
            ]
        },
        {
            "taskId": "Task_115",
            "projectId": "youhuixianxiang",
            "name": "机酒优惠享问题修复",
            "content": "黄启孟提出机酒优惠享的问题，蔡宜身和谭鹏yy确认环境不稳定并在调整中。",
            "createTime": "2024-10-22T13:28:54.014Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "1428",
                "1429",
                "1430",
                "1431",
                "1432",
                "1442",
                "1443",
                "1444",
                "1445",
                "1446",
                "1447"
            ]
        },
        {
            "taskId": "Task_116",
            "projectId": "youhuixianxiang",
            "name": "订单详情页待还款状态交互确认",
            "content": "赵苗m与郝泽楠确认订单详情页待还款状态的交互方式，并与产品电话沟通确定。",
            "createTime": "2024-10-22T13:42:55.494Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "discussion",
            "assigneeId": "赵苗m",
            "creatorId": "赵苗m",
            "messageIds": [
                "1433",
                "1434"
            ]
        },
        {
            "taskId": "Task_117",
            "projectId": "youhuixianxiang",
            "name": "支付中心商户号用途确认",
            "content": "何钢向丁家新请教支付中心商户号的具体用途，丁家新解释了merchantCode的用途。",
            "createTime": "2024-10-23T06:34:46.306Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "question",
            "assigneeId": "何钢",
            "creatorId": "何钢",
            "messageIds": [
                "1497",
                "1498",
                "1500",
                "1502",
                "1505",
                "1511",
                "1515"
            ]
        },
        {
            "taskId": "Task_123",
            "projectId": "youhuixianxiang",
            "name": "售后方案排期",
            "content": "售后方案对出来了，这周应该要排",
            "createTime": "2024-10-23T14:38:42Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "尹凯",
            "creatorId": "朱秋阳",
            "messageIds": [
                "1501",
                "1503",
                "1504",
                "1509",
                "1510",
                "1534"
            ]
        },
        {
            "taskId": "Task_124",
            "projectId": "youhuixianxiang",
            "name": "支付中心商户号用途确认",
            "content": "确认支付中心的商户号用途，除了标记业务方和参数校验外，还有其他用途。",
            "createTime": "2024-10-23T14:34:46Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "question",
            "assigneeId": "丁家新",
            "creatorId": "何钢",
            "messageIds": [
                "1497",
                "1498",
                "1500",
                "1505",
                "1511",
                "1512",
                "1515",
                "1517"
            ]
        },
        {
            "taskId": "Task_125",
            "projectId": "youhuixianxiang",
            "name": "收银台batchSeq字段含义确认",
            "content": "确认收银台的batchSeq字段在合单和非合单场景下的值。",
            "createTime": "2024-10-23T14:57:59Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "question",
            "assigneeId": "肖杨",
            "creatorId": "蔡宜身",
            "messageIds": [
                "1521",
                "1522",
                "1523",
                "1525",
                "1526",
                "1540",
                "1541"
            ]
        },
        {
            "taskId": "Task_126",
            "projectId": "youhuixianxiang",
            "name": "保险场景二次拉起先付逻辑实现",
            "content": "在保险场景下，二次拉起时需要重新调用cashierInfo接口，判断cashierJumpUrl是否存在来决定拉起后付还是先付。",
            "createTime": null,
            "deadline": null,
            "status": null,
            "priority": null,
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": null,
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "1570",
                "1571",
                "1572",
                "1574",
                "1575",
                "1576",
                "1577",
                "1580",
                "1581",
                "1582",
                "1584",
                "1585",
                "1586",
                "1587"
            ]
        },
        {
            "taskId": "Task_127",
            "projectId": "youhuixianxiang",
            "name": "售前主流程/交易/辅营",
            "content": "售前阻塞在支付前校验，待支付中心联调，目前售前剩余授权回调验证 还得1pd调通，跑case 2pd。前端依赖环境跑通，改动需要1pd，跑case 1pd。obs收银台待联调跑case，无工时。后服务联调进度正常，问题无，跑case 0.5pd。",
            "createTime": "2024-10-23T09:17:40.08Z",
            "deadline": "2024-10-30T00:00:00Z",
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "feature",
            "assigneeId": "蔡宜身",
            "creatorId": "蔡宜身",
            "messageIds": [
                "1597"
            ]
        },
        {
            "taskId": "Task_128",
            "projectId": "youhuixianxiang",
            "name": "售前提测时间同步",
            "content": "同步售前提测时间，确保与其他团队排期一致。",
            "createTime": "2024-10-23T09:18:13.939Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "coordination",
            "assigneeId": null,
            "creatorId": "蔡宜身",
            "messageIds": [
                "1599",
                "1611",
                "1612"
            ]
        },
        {
            "taskId": "Task_129",
            "projectId": "youhuixianxiang",
            "name": "支付中心创单请求参数确认",
            "content": "确认支付中心创单请求参数，确保商户单号传递正确。",
            "createTime": "2024-10-23T09:33:42.567Z",
            "deadline": null,
            "status": "pending",
            "priority": "medium",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "coordination",
            "assigneeId": null,
            "creatorId": "谭鹏yy",
            "messageIds": [
                "1601",
                "1602",
                "1603"
            ]
        },
        {
            "taskId": "Task_130",
            "projectId": "youhuixianxiang",
            "name": "测试环境问题排查",
            "content": "排查测试环境问题，确保营销生单成功。",
            "createTime": "2024-10-24T08:51:52.578Z",
            "deadline": null,
            "status": "in_progress",
            "priority": "high",
            "reminderCount": null,
            "lastRemindTime": null,
            "taskType": "bug_fix",
            "assigneeId": null,
            "creatorId": null,
            "messageIds": [
                "1640",
                "1641",
                "1642",
                "1643",
                "1644",
                "1645",
                "1646",
                "1647",
                "1648",
                "1649",
                "1650",
                "1651",
                "1652",
                "1653",
                "1654",
                "1655",
                "1656",
                "1657",
                "1658",
                "1659",
                "1660",
                "1661",
                "1662",
                "1663",
                "1664",
                "1665",
                "1666",
                "1667",
                "1668",
                "1669",
                "1670",
                "1671",
                "1672",
                "1673",
                "1674",
                "1675",
                "1676",
                "1677",
                "1678",
                "1679",
                "1680",
                "1681",
                "1682",
                "1683",
                "1684",
                "1685",
                "1686",
                "1687",
                "1688",
                "1689",
                "1690",
                "1691",
                "1692",
                "1693",
                "1694",
                "1695",
                "1696",
                "1697",
                "1698"
            ]
        }
    ],
    "processingIssues": [
        {
            "issueId": "Issue_17",
            "name": "国内支付完成页缺少独立酒店模块",
            "projectId": "youhuixianxiang",
            "description": "国内支付完成页没有UI设计中的独立酒店模块。",
            "raiseTime": "2024-10-08T21:04:20Z",
            "resolveTime": null,
            "status": "open",
            "severity": "medium",
            "issueType": "bug",
            "referenceCount": 1,
            "lastMentionTime": "1970-01-01T00:33:44Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": null
        },
        {
            "issueId": "Issue_10",
            "name": "实时查询耗时过长",
            "projectId": "youhuixianxiang",
            "description": "实时查询耗时过长，booking用不了，需要P100在50以下。",
            "raiseTime": "2024-09-24T10:56:51Z",
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": 5,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "56",
                "57",
                "58",
                "59",
                "60"
            ]
        },
        {
            "issueId": "Issue_12",
            "name": "支付完成页和订单详情页需求确认问题",
            "projectId": "youhuixianxiang",
            "description": "@郝泽楠 确认支付完成页和订单详情页是否只做app版本，并且是否需要考虑合单逻辑。",
            "raiseTime": "2024-09-26T08:30:13.163Z",
            "resolveTime": null,
            "status": "open",
            "severity": "medium",
            "issueType": "question",
            "referenceCount": 3,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "166",
                "167",
                "170"
            ]
        },
        {
            "issueId": "Issue_19",
            "name": "@郝泽楠 这个是前端判断吗？",
            "projectId": "youhuixianxiang",
            "description": "@郝泽楠 这个是前端判断吗？",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": 1,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "149"
            ]
        },
        {
            "issueId": "Issue_9",
            "name": "查询任务详情接口逻辑不一致",
            "projectId": "youhuixianxiang",
            "description": "查询任务详情接口逻辑需要与火车票保持一致，即list和ota走缓存，booking走实时查。",
            "raiseTime": "2024-09-24T10:51:42Z",
            "resolveTime": null,
            "status": "in_progress",
            "severity": "medium",
            "issueType": "question",
            "referenceCount": 6,
            "lastMentionTime": "2024-09-24T11:21:27Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "51",
                "52",
                "53",
                "54",
                "55",
                "56"
            ]
        },
        {
            "issueId": "Issue_18",
            "name": null,
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": 0,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_11",
            "name": "数据结构不一致问题",
            "projectId": "youhuixianxiang",
            "description": "赵苗m指出赵述佳提供的数据结构与需求不一致，需要进行适配。",
            "raiseTime": "2024-09-26T07:56:57.221Z",
            "resolveTime": null,
            "status": "open",
            "severity": "medium",
            "issueType": "bug",
            "referenceCount": 2,
            "lastMentionTime": "2024-09-26T08:00:02.659Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "159",
                "162"
            ]
        },
        {
            "issueId": "Issue_20",
            "name": "@赵苗m 这个是我这的返回 你可以先参考一下",
            "projectId": "youhuixianxiang",
            "description": "@赵苗m 这个是我这的返回 你可以先参考一下",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": 1,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "151"
            ]
        },
        {
            "issueId": "Issue_21",
            "name": "支付中心返回链接类型不明确",
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": "",
            "severity": null,
            "issueType": null,
            "referenceCount": null,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_22",
            "name": null,
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": 0,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_23",
            "name": "填单页服务器异常",
            "projectId": "youhuixianxiang",
            "description": "填单页出现502服务器异常，影响联调进度。",
            "raiseTime": "2024-10-12T20:52:04Z",
            "resolveTime": null,
            "status": "open",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 5,
            "lastMentionTime": "2024-10-15T11:12:22Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "584",
                "585",
                "592",
                "593",
                "666",
                "667"
            ]
        },
        {
            "issueId": "Issue_24",
            "name": "@蔡宜身 填单页 还是不行啊 502",
            "projectId": "youhuixianxiang",
            "description": "@蔡宜身 填单页 还是不行啊 502",
            "raiseTime": "2024-10-14T04:14:01.683Z",
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": null,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_27",
            "name": "环境冲突问题",
            "projectId": "youhuixianxiang",
            "description": "两个环境有冲突，导致没有主站标识。",
            "raiseTime": "2024-10-15T15:02:54Z",
            "resolveTime": null,
            "status": "open",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 2,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "768",
                "769",
                "770"
            ]
        },
        {
            "issueId": "Issue_31",
            "name": "",
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": null,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_32",
            "name": "支付公钥验签失败",
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": 0,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_33",
            "name": null,
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": null,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_34",
            "name": "带保险场景下支付问题",
            "projectId": "youhuixianxiang",
            "description": "在带保险的场景下，支付传的授权金额不正确，导致支付失败。",
            "raiseTime": "2024-10-22T16:48:48Z",
            "resolveTime": null,
            "status": "open",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 2,
            "lastMentionTime": "2024-10-22T17:08:17Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "1342",
                "1349"
            ]
        },
        {
            "issueId": "Issue_35",
            "name": "支付流程倒计时过长",
            "projectId": "youhuixianxiang",
            "description": "@郝泽楠 提出支付流程中的倒计时默认设置为两小时，建议调整为15分钟。",
            "raiseTime": "2024-10-22T17:12:36Z",
            "resolveTime": null,
            "status": "open",
            "severity": "medium",
            "issueType": "question",
            "referenceCount": 2,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "1358",
                "1359"
            ]
        },
        {
            "issueId": "Issue_41",
            "name": "支付前校验阻塞售前主流程提测",
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": null,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "1592",
                "1595"
            ]
        },
        {
            "issueId": "Issue_42",
            "name": null,
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": null,
            "severity": null,
            "issueType": null,
            "referenceCount": null,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_43",
            "name": "支付中心联调阻塞",
            "projectId": "youhuixianxiang",
            "description": "空",
            "raiseTime": null,
            "resolveTime": null,
            "status": "",
            "severity": "",
            "issueType": "",
            "referenceCount": null,
            "lastMentionTime": null,
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        }
    ],
    "doneIssues": [
        {
            "issueId": "Issue_25",
            "name": "填单页异常问题",
            "projectId": "youhuixianxiang",
            "description": "填单页出现异常，可能是环境问题导致。",
            "raiseTime": "2024-10-15T11:12:18Z",
            "resolveTime": "2024-10-15T11:22:35Z",
            "status": "resolved",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 2,
            "lastMentionTime": "2024-10-15T11:22:35Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "666",
                "667"
            ]
        },
        {
            "issueId": "Issue_26",
            "name": "机酒优惠享问题",
            "projectId": "youhuixianxiang",
            "description": "机酒优惠享功能无法正常使用，需检查Apollo接口参数。",
            "raiseTime": "2024-10-15T11:15:06Z",
            "resolveTime": "2024-10-15T18:03:54Z",
            "status": "resolved",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 5,
            "lastMentionTime": "2024-10-15T18:03:54Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "672",
                "673",
                "675",
                "676",
                "678",
                "679",
                "680",
                "681",
                "682",
                "683",
                "684",
                "685",
                "686",
                "688",
                "689"
            ]
        },
        {
            "issueId": "Issue_28",
            "name": "数据缺失问题",
            "projectId": "youhuixianxiang",
            "description": "黄启孟提到他这里一直没有数据。",
            "raiseTime": "2024-10-15T15:06:12Z",
            "resolveTime": "2024-10-15T18:03:54Z",
            "status": "resolved",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 3,
            "lastMentionTime": "2024-10-15T18:03:54Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": []
        },
        {
            "issueId": "Issue_29",
            "name": "环境冲突问题",
            "projectId": "youhuixianxiang",
            "description": "两个环境可能有冲突，导致主站标识消失。",
            "raiseTime": "2024-10-15T15:02:54Z",
            "resolveTime": "2024-10-15T15:04:33Z",
            "status": "resolved",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 2,
            "lastMentionTime": "2024-10-15T15:04:33Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "768",
                "769",
                "770"
            ]
        },
        {
            "issueId": "Issue_30",
            "name": "数据缺失问题",
            "projectId": "youhuixianxiang",
            "description": "黄启孟报告数据缺失问题，赵述佳询问是否有trace，黄启孟提供了trace信息。",
            "raiseTime": "2024-10-15T15:06:12Z",
            "resolveTime": "2024-10-15T15:07:12Z",
            "status": "resolved",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 2,
            "lastMentionTime": "2024-10-15T15:07:12Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "771",
                "772",
                "773"
            ]
        },
        {
            "issueId": "Issue_36",
            "name": "营销活动处理问题",
            "projectId": "youhuixianxiang",
            "description": "多个营销活动存在一个activityNum，对应多个营销，其中一个营销才是信用付营销，交易这得拆价格，才能返好",
            "raiseTime": "2024-10-22T15:33:11Z",
            "resolveTime": "2024-10-22T15:33:29Z",
            "status": "resolved",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 1,
            "lastMentionTime": "2024-10-22T15:33:29Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "1324",
                "1325"
            ]
        },
        {
            "issueId": "Issue_38",
            "name": "支付完成页问题",
            "projectId": "youhuixianxiang",
            "description": "支付完成页存在标题图片大小、标签样式、模块底部空白和i标浮层内容等问题。",
            "raiseTime": "2024-10-22T12:15:10.321Z",
            "resolveTime": null,
            "status": "open",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 3,
            "lastMentionTime": "2024-10-22T13:02:58.359Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "1387",
                "1403",
                "1404",
                "1420",
                "1425",
                "1426"
            ]
        },
        {
            "issueId": "Issue_39",
            "name": "机酒优惠享问题",
            "projectId": "youhuixianxiang",
            "description": "机酒优惠享功能存在问题，无法正常使用。",
            "raiseTime": "2024-10-22T13:28:54.014Z",
            "resolveTime": null,
            "status": "in_progress",
            "severity": "high",
            "issueType": "bug",
            "referenceCount": 5,
            "lastMentionTime": "2024-10-23T02:56:01.919Z",
            "raiseId": null,
            "solverId": null,
            "messageIds": [
                "1428",
                "1429",
                "1430",
                "1431",
                "1432",
                "1442",
                "1443",
                "1444",
                "1445",
                "1446",
                "1447"
            ]
        }
    ]
}